version: '3.8'

services:
  tdah-app:
    build: .
    container_name: tdah-presentation
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tdah.rule=Host(`seu-dominio.com`)"
      - "traefik.http.routers.tdah.entrypoints=websecure"
      - "traefik.http.routers.tdah.tls.certresolver=letsencrypt"
      - "traefik.http.services.tdah.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true

